### ISSUE TITLE
Initial thoughts on DB Schema

### ISSUE THREAD

**Issue by MichaelSchwar3** [agronv/notefloat#1]
Username
Do we need both username and e-mail or just one?

Tracks
Need to account for AWS Active Storage for Track file
Missing index on album_id and user_id in tracks

Comments
Missing foreign key for album? tracks?

Overall nice work on this schema, just a few small things to think about

**Comment by agronv** [comment]
Username 
-    In SoundCloud the user does have both a username and email, and i feel like having both won't 
      really hurt 
-   I also added a image_url and description to user

Tracks 
-   I added an image url to the tracks and I'm thinking about also added a description 

Comments 
-   I forgot to do that I added them now
-   I added a parent comment id (people can comment on others comments)

Albums
-   I decided to completely get rid of albums, no one really posts albums on SoundCloud and when 
    they do it's usually as 2 hour long tracks. Having albums which be a lot more work for almost no 
    benefits

Likes 
-   I decided to add likes, users will be able to like songs and on there page it will show liked songs, 
    and the count of likes on a song will increase.

I will also update my MVP list

**Comment by MichaelSchwar3** [comment]
That all sounds great to me.

Updated schema looks good. Looking forward to seeing the built app.
